apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
    - name: goserver-service
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30001 # >30.000 and <32767
